# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:46+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, RootModel


class Extension(BaseModel):
    avg_rating: Optional[float] = None
    extension_id: Optional[int] = None
    install_count: Optional[int] = None
    prev_avg_rating: Optional[float] = None
    prev_install_count: Optional[int] = None
    prev_rating_count: Optional[int] = None
    rating_count: Optional[int] = None
    update_ts: Optional[datetime] = None
    url: Optional[AnyUrl] = None


class UserExtensionsGetResponse(RootModel[List[Extension]]):
    root: List[Extension]
